apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort            # Good for local / minikube demos
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080
  selector:
    app: flask
    version: blue           # Start routing to blue
